// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjr4sYewPAG7hPEVhBXGSoRvDJWhegESs',
    appId: '1:380999269272:web:9d8a16e561267d8bb189ed',
    messagingSenderId: '380999269272',
    projectId: 'healplus-7eca1',
    authDomain: 'healplus-7eca1.firebaseapp.com',
    databaseURL: 'https://healplus-7eca1-default-rtdb.firebaseio.com',
    storageBucket: 'healplus-7eca1.firebasestorage.app',
    measurementId: 'G-9XEM3CMM88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTKh_m4A5IIplgJay1u-EtLRanfxvhH3g',
    appId: '1:380999269272:android:1967588ce135d09bb189ed',
    messagingSenderId: '380999269272',
    projectId: 'healplus-7eca1',
    databaseURL: 'https://healplus-7eca1-default-rtdb.firebaseio.com',
    storageBucket: 'healplus-7eca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8vgAo6OwvaKeXRMh8TMXokS6fsc1veDE',
    appId: '1:380999269272:ios:9f26d9e9e447689cb189ed',
    messagingSenderId: '380999269272',
    projectId: 'healplus-7eca1',
    databaseURL: 'https://healplus-7eca1-default-rtdb.firebaseio.com',
    storageBucket: 'healplus-7eca1.firebasestorage.app',
    iosBundleId: 'com.example.healplusPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8vgAo6OwvaKeXRMh8TMXokS6fsc1veDE',
    appId: '1:380999269272:ios:9f26d9e9e447689cb189ed',
    messagingSenderId: '380999269272',
    projectId: 'healplus-7eca1',
    databaseURL: 'https://healplus-7eca1-default-rtdb.firebaseio.com',
    storageBucket: 'healplus-7eca1.firebasestorage.app',
    iosBundleId: 'com.example.healplusPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjr4sYewPAG7hPEVhBXGSoRvDJWhegESs',
    appId: '1:380999269272:web:f0ae4c5cd50ad058b189ed',
    messagingSenderId: '380999269272',
    projectId: 'healplus-7eca1',
    authDomain: 'healplus-7eca1.firebaseapp.com',
    databaseURL: 'https://healplus-7eca1-default-rtdb.firebaseio.com',
    storageBucket: 'healplus-7eca1.firebasestorage.app',
    measurementId: 'G-32YDLSNHZR',
  );
}
